language: cpp 
dist: focal
compiler: gcc
os: linux

# safelist
branches:
  only:
  - main

cache: # see https://docs.travis-ci.com/user/caching/
- directories:
  - $HOME/.cache

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get -y install gcc-10 g++-10
  - sudo apt-get -y install lcov cppcheck

install:
  # (fake) install dependencies (usually involves wget, configure, make, ...)
  # install into cache folder (build binaries+headers only, no sources and do NOT build there)
  - mkdir -p $HOME/.cache
  - touch $HOME/.cache/mydependency.so
  # /usr/bin/gcc points to an older compiler on Linux.
  - if [ "$CXX" = "g++" ]; then export CXX="g++-10" CC="gcc-10"; fi

script:
  - ./travis.sh

after_success:
# Create lcov report
# capture coverage info
- lcov --directory . --capture --output-file coverage.info
# filter out system and extra files.
# To also not include test code in coverage add them with full path to the patterns: '*/tests/*'
- lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
# output coverage data for debugging (optional)
- lcov --list coverage.info
# Uploading to CodeCov
# '-f' specifies file(s) to use and disables manual coverage gathering and file search which has already been done above
- bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"